package controller

import (
	"net"
	"net/http"
	"net/http/fcgi"
	"path"
	"strings"
	"time"

	"github.com/yookoala/gofast"
)

const (
	fastCGIVersion1    = 1
	fastCGIDialTimeout = 10 * time.Second
)

type fastCGIProxy struct {
	handler http.Handler
	dial    func() (net.Conn, error)
}

func newFastCGIProxy(targetAddress string) *fastCGIProxy {
	proxy := &fastCGIProxy{}
	dialer := &net.Dialer{Timeout: fastCGIDialTimeout, KeepAlive: 30 * time.Second}
	proxy.dial = func() (net.Conn, error) {
		return dialer.Dial("tcp", targetAddress)
	}

	session := gofast.Chain(
		gofast.BasicParamsMap,
		gofast.MapHeader,
		preserveInboundFastCGIParams,
	)(gofast.BasicSession)
	proxy.handler = gofast.NewHandler(
		session,
		gofast.SimpleClientFactory(func() (net.Conn, error) {
			return proxy.dial()
		}),
	)
	return proxy
}

func (proxy *fastCGIProxy) ServeHTTP(writer http.ResponseWriter, request *http.Request) {
	proxy.handler.ServeHTTP(writer, request)
}

// preserveInboundFastCGIParams copies parameters that net/http/fcgi retains in
// the request context, such as SCRIPT_FILENAME and DOCUMENT_ROOT. Parameters
// represented directly by http.Request are generated by gofast middleware.
func preserveInboundFastCGIParams(inner gofast.SessionHandler) gofast.SessionHandler {
	return func(client gofast.Client, request *gofast.Request) (*gofast.ResponsePipe, error) {
		for name, value := range fcgi.ProcessEnv(request.Raw) {
			request.Params[name] = value
		}
		if request.Params["REQUEST_URI"] == "" && request.Raw.URL != nil {
			request.Params["REQUEST_URI"] = request.Raw.URL.RequestURI()
		}
		if request.Params["SCRIPT_NAME"] == "" {
			filename := request.Params["SCRIPT_FILENAME"]
			documentRoot := strings.TrimSuffix(request.Params["DOCUMENT_ROOT"], "/")
			switch {
			case filename != "" && documentRoot != "" && strings.HasPrefix(filename, documentRoot+"/"):
				request.Params["SCRIPT_NAME"] = strings.TrimPrefix(filename, documentRoot)
			case filename != "":
				request.Params["SCRIPT_NAME"] = "/" + path.Base(filename)
			case request.Raw.URL != nil:
				request.Params["SCRIPT_NAME"] = request.Raw.URL.Path
			}
		}
		if request.Params["PATH_INFO"] == "" && request.Raw.URL != nil {
			scriptName := request.Params["SCRIPT_NAME"]
			if scriptName != "" && strings.HasPrefix(request.Raw.URL.Path, scriptName+"/") {
				request.Params["PATH_INFO"] = strings.TrimPrefix(request.Raw.URL.Path, scriptName)
			}
		}
		return inner(client, request)
	}
}
